### ISSUE TITLE
format does not work on 28th of February

### ISSUE THREAD

**Issue by pete911** [icza/gox#10]
I have a test where I set exact expiry date and then test if the format is printed correctly. My tests started failing today (28th of February), because I am missing 2 days. This is output from my test:
```
expected: "3 years 2 months 7 days 5 hours 25 minutes"
actual  : "3 years 2 months 5 days 5 hours 25 minutes"
```
All I am doing in the test is creating a future time:
```
func getTime(years, months, days, hours, minutes int) time.Time {
	return time.Now().AddDate(years, months, days).
		Add(time.Hour*time.Duration(hours) + time.Minute*time.Duration(minutes))
}
```
And then comparing time that is formatted by (where `t` is the time generated by `getTime` function):
```
year, month, day, hour, minute, _ := timex.Diff(time.Now(), t)
```

**Comment by icza** [comment]
Please provide exact input and expected output where you think it's wrong. Aim for a minimal, reproducible example.

**Comment by pete911** [comment]
@icza thanks for quick reply, just add this to the `timex/timex_test.go` file:
```
func TestFeb(t *testing.T) {
	futureYears := 3
	futureMonths := 2
	futureDays := 7
	futureHours := 5
	futureMinutes := 25
	futureTime := time.Now().AddDate(futureYears, futureMonths, futureDays).Add(time.Hour*time.Duration(futureHours) + time.Minute*time.Duration(futureMinutes))
	year, month, day, hour, minute, _ := Diff(time.Now(), futureTime)
	fmt.Printf("year: %d month: %d day: %d hour: %d minute: %d\n", year, month, day, hour, minute)
}
```
run it and have a look that I am passing future days 7 but it prints days 5. I think the problem is on line 49 in `timex.go`.

**Comment by pete911** [comment]
@icza feel free to close the PR, it looks like there's some problem how go handles dates:
```
	futureYears := 0
	futureMonths := 1
	futureDays := 7
	futureTime := time.Now().AddDate(futureYears, futureMonths, futureDays)
	fmt.Println(futureTime)
```
output
```
2023-04-04 15:15:21.148444 +0100 BST
```
I would expect output to be 7ht of April ... so yeah, looks like the issue here, even before it calls your library.

**Comment by icza** [comment]
There's bo error here, just an interpretation difference.

If you add 1 month and 1 to Feb 28, you can do it in 2 ways: you may add the month first then the day, then you get March 29. If you add the day first then the month, you get April 1.

I'm not at my computer, can't write more, but I think you get the idea.

**Comment by pete911** [comment]
sure, thanks for help. I'm closing the issue
