### ISSUE TITLE
An Apache 2.0 licence but no copyright information

### ISSUE THREAD

**Issue by andrehaland** [icza/gox#4]
According to the Apache 2.0 license:

``` 
"Work" shall mean the work of authorship, whether in Source or
Object form, made available under the License, as indicated by a
copyright notice that is included in or attached to the work
(an example is provided in the Appendix below).
```

```
APPENDIX: How to apply the Apache License to your work.

To apply the Apache License to your work, attach the following
boilerplate notice, with the fields enclosed by brackets "{}"
replaced with your own identifying information. (Don't include
the brackets!)  The text should be enclosed in the appropriate
comment syntax for the file format. We also recommend that a
file or class name and description of purpose be included on the
same "printed page" as the copyright notice for easier
identification within third-party archives.

   Copyright {yyyy} {name of copyright owner}
```

I want to attribute the work in this repo, but I could not find any such copyright notices in any of the source files. To me it is unclear how the Apache 2.0 License works without copyright notice. Is this something you could fix @icza?

**Extra information**
The "Redistribution" of the Apache 2.0 Licence applies to the "Work", which (as stated above) is indicated by a copyright notice.
```
Redistribution. You may reproduce and distribute copies of the
Work or Derivative Works thereof in any medium, with or without
modifications, and in Source or Object form, provided that You
meet the following conditions:      
```

**Comment by icza** [comment]
I'm not a layer, I'm not sure exactly what the license demands. How would a fix look like?

To me it is enough to indicate the code originates from https://github.com/icza/gox.

**Comment by andrehaland** [comment]
As I understand the license you need to add a copyright notice at the top of your source files. So for instance something like:
```go
// Copyright 2021 icza
// Use of this source code is governed by an Apache 2.0
// license that can be found in the LICENSE file.
package timex

...
```

**Comment by icza** [comment]
It looks including it in the header of every source file is not required as long as the complete license is included in the top of the source tree in the LICENSE file. It's just more of a recommendation. If so, I do not wish to modify all files.

Source: https://softwareengineering.stackexchange.com/questions/317041/should-i-add-the-license-in-every-header-and-source-file
