### ISSUE TITLE
Unexpected mathx.Round() result when rounding to 2 decimal places

### ISSUE THREAD

**Issue by Dmitrevicz** [icza/gox#8]
I've ran into some difficulties when tried to find a way to round float64 values to 2 decimal places. Maybe smn can explain am I wrong or suggest a solution, if exists.
_P.S. I know about IEEE-754 floating point standard_

I've found 2 values that rounds in a way I don't expect - `1.275` and `4.935`.

`1.275` is expected to become `1.28` (but I get `1.27`)
`4.935` is expected to become `4.94` (but I get `4.93`)

Example code (Go version 1.19):
```
package main

import (
	"fmt"

	"github.com/icza/gox/mathx"
)

func main() {
	print(2.345, 0.01, 2.35) // ok
	print(1.275, 0.01, 1.28) // fail #1
	print(4.935, 0.01, 4.94) // fail #2
}

func print(f, unit, exp float64) {
	rounded := mathx.Round(f, unit)
	fmt.Printf("input: %.3f | got: %.3f | expected: %.3f\n", f, rounded, exp)
}

```

Output:
```
input: 2.345 | got: 2.350 | expected: 2.350
input: 1.275 | got: 1.270 | expected: 1.280
input: 4.935 | got: 4.930 | expected: 4.940
```

Are my expectations wrong?

_Managed to workaround it in the next code, but I'm not sure if it will fix everything and not break smth else:_
```
func round2(f float64) float64 {
	// return math.Floor(f*100+0.5) / 100.0 // same rounding issue as mathx.Round(f, 0.01)
	// return math.Floor(f*100+0.5+1e-14) / 100.0 // fixes 1.275, but not 4.935
	return math.Floor(f*100+0.5+1e-13) / 100.0 // 1e-13 helps with both 1.275 and 4.935
}
// problem is when I multiply by 100 and then rounding breaks
// 1) 1.275 * 100 = 127.49999999999999 (instead of 127.5)
// 2) 4.935 * 100 = 493.49999999999994
```

**Comment by icza** [comment]
You want to pass `1.275` to `mathx.Round()` and expect to get `1.28`. But you can't pass `1.275` as a `float64` because there is no `float64` value being exactly `1.275`.

**Comment by Dmitrevicz** [comment]
Thanks for your answers
